### ISSUE TITLE
Uncaught Error: Call to undefined method React\EventLoop\Timer\Timer::setData()

### ISSUE THREAD

**Issue by SilentBackend** [nrk/predis-async#30]
Hi Team,

I am using this plugin into my project.

I am getting the following error in my project logs...Can someone plz help on this

My s/w specification:

Php 7.0
"predis/predis": "1.1.1",
"predis/predis-async": "dev-master"

PHP Fatal error:  Uncaught Error: Call to undefined method React\EventLoop\Timer\Timer::setData() in /var/www/html/vendor/predis/predis-async/src/Connection/AbstractConnection.php:179
Stack trace:
#0 /var/www/html/vendor/predis/predis-async/src/Connection/AbstractConnection.php(158): Predis\Async\Connection\AbstractConnection->armTimeoutMonitor(5, Object(Closure))
#1 /var/www/html/vendor/predis/predis-async/src/Connection/AbstractConnection.php(209): Predis\Async\Connection\AbstractConnection->createResource(Object(Closure))
#2 /var/www/html/vendor/predis/predis-async/src/Client.php(178): Predis\Async\Connection\AbstractConnection->connect(Object(Closure))
#3 /var/www/html/commands/Queue/QueueConnector.php(86): Predis\Async\Client->connect(Object(Closure))
#4 /var/www/html/commands/Queue/QueueConnector.php(43): CLI\Queue\QueueConnector->createRedisClient(Object(CLI\Configuration\Configuration), Object(CLI\Handler\s3UploadHandler))
#5 /var/www/html/commands/Jobs/S3Upload.php(13): CLI\Queue\QueueConnector->__construct(Object(CLI in /var/www/html/vendor/predis/predis-async/src/Connection/AbstractConnection.php on line 179

Thanks in advance

**Comment by mathus13** [comment]
Fixed this by downgrading to react/event-loop. Seems this call was removed in 0.5
`composer require react/event-loop ^0.4`

**Comment by voodooism** [comment]
> Fixed this by downgrading to react/event-loop. Seems this call was removed in 0.5
> `composer require react/event-loop ^0.4`

It is works for me!
